export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "./globals.css";

import "./globals.css";
import NextAuthProvider from "./NextAuthProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
