export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "./globals.css";
import NextAuthProvider from "./NextAuthProvider";
import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className="font-sans">
        <NextAuthProvider>
          {children}
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
